
spring:
  application:
    name: t2t

  devtools:
    restart:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/t2t?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test1
    password: 1234

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB

file.dir: E:\moon\framework\uploadt2t\
#uploadfile.dir: D:\\project\\t2t\\src\\main\\resources\\static\\upload\\
#movingfile.from: profile\\temp\\
#movedfile.to: profile\\
HTTP_SESSION_USER: t2t_session_user

mybatis:
  mapper-locations: classpath:mapper/*.xml
  # MyBatis Settings
  type-aliases-package: org.t2t.mem.dto

logging:
  level:
    org.springframework.jdbc: debug
    org.apache.coyote.http11: trace
    org.k8go4go.miniboard.mapper: trace

server:
  servlet:
    context-path: /

